<script>

    console.log('1')

    // fetch API 사용
    // 예제를 위하여 JSON placeholder 사이트에서 Sample Data 활용
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(function(response) {
        return response.json();
    })
    // 상위 then 에서 return 한 json 값을 매개변수로 넘겨 줌
    .then(function(myJson) {
        console.log(myJson);
    }) 
    
    console.log('2');

    // console.log() 1 과 2 과 출력이 먼저 되고 비동기인 fetch 가 나중에 출력이 됨
    // 위 then 이 바로 Promise 임 

    // 공식 문서에서 fetch 는 Promise 를 return 한다고 함
    var fetched = fetch('https://jsonplaceholder.typicode.com/posts');
    // fetch 함수는 Promise 객체를 return 함
    // Promise 객체를 리턴 시 비동기적으로 작동하는 함수일 확률이 높음
    console.log('페치드 : ' + fetched);

    // then 과 catch 모두 둘 다 callback 함수를 받음
    // then 은 fetch 를 통한 결과가 성공하였을 시 then 을 사용하여 호출
    fetched.then(function(result) {
        // Response 타입의 객체가 리턴이 됨 
        // A Promise that resolves to a Response object.
        // Promise 가 성공 시 Response 객체를 반환
        console.log('then result :' , result);
    });
    
    // Promise 함수가 실패 하였을 시 catch 를 호출
    fetched.catch(function (reason){
        // catch 는 fetch 가 실패하였을 시 에만 작동을 함 
        console.log('reason', reason);
    });

    // Fetch 는 일반적으로 변수를 사용하지 않고
    // 보통 이런식으로 then catch 를 바로 연결하여 사용을 함 
    fetch('https://jsonplaceholder.typicode.com/posts')
        .then(function(response) {
            // Response 객체를 출력
            console.log('response ', response);
            // 가져온 데이터를 출력
            // Response 객체에는 text() 도 있도 있고 json() 도 있음
            // response.json() 을 사용시 Promise 객체를 Return 함 
            // console.log('response json: ' ,  response.json());
            // console.log('response text : ' , response.text());

            // Promise 를 반환하는 함수는 then 과 catch 사용이 가능함
            // response.json().then(function(data){
            //     console.log('json() data', data);
            // }) 

            // 보통은 이런식으로 return 을 함
            // Promise 객체가 리턴 시 then 을 사용하여 callback 함수를 이용 하여 데이터를 가져 옴  
            return response.json();

        })   
        .catch(function(reason) {
            console.log('reason ' , reason);
        })

        // then 안에 또 then 이 들어가는 방식은 Nested Promise 라고 함 
        // 보통 Chaining 방식을 사용
        // 또 한 가지 방법은 Promise 객체를 리턴하여 promise chaining 방식으로 사용

        // Promise 를 사용 시 그 즉시는 Pending 상태 임
        // 그 다음 Resolve 시 then() 을 사용하요 이용 
        // catch 는 Reject 하였을 시 사용 (Promise 사용 실패 시)

        // then 이건 catch 건 사용 후 다시 Pending 처리로 됨



</script>